const gejala = [
  { kode: "G01", nama: "Memiliki jadwal belajar" },
  { kode: "G02", nama: "Belajar setiap hari" },
  { kode: "G03", nama: "Mengerjakan tugas tepat waktu" },
  { kode: "G04", nama: "Memiliki target belajar" },
  { kode: "G05", nama: "Membuat catatan materi" },
  { kode: "G06", nama: "Mengulang materi kuliah" },
  { kode: "G07", nama: "Mengikuti perkuliahan dengan baik" },
  { kode: "G08", nama: "Datang kuliah tepat waktu" },
  { kode: "G09", nama: "Aktif bertanya saat belajar" },
  { kode: "G10", nama: "Membaca referensi tambahan" },

  { kode: "G11", nama: "Sering menunda tugas" },
  { kode: "G12", nama: "Sering bermain game" },
  { kode: "G13", nama: "Sering membuka media sosial" },
  { kode: "G14", nama: "Tidur larut malam" },
  { kode: "G15", nama: "Sulit fokus belajar" },
  { kode: "G16", nama: "Tidak memiliki jadwal" },
  { kode: "G17", nama: "Tidak memiliki target" },
  { kode: "G18", nama: "Sering terlambat mengumpulkan tugas" },
  { kode: "G19", nama: "Jarang belajar" },
  { kode: "G20", nama: "Mudah terdistraksi" },

  { kode: "G21", nama: "Menggunakan jadwal harian" },
  { kode: "G22", nama: "Membuat daftar tugas" },
  { kode: "G23", nama: "Menyelesaikan tugas sebelum deadline" },
  { kode: "G24", nama: "Membatasi penggunaan media sosial" },
  { kode: "G25", nama: "Memanfaatkan waktu luang untuk belajar" },

  { kode: "G26", nama: "Sering menonton video hiburan saat belajar" },
  { kode: "G27", nama: "Sering berpindah tugas tanpa selesai" },
  { kode: "G28", nama: "Belajar hanya saat menjelang ujian" },
  { kode: "G29", nama: "Tidak memiliki prioritas pekerjaan" },
  { kode: "G30", nama: "Mengabaikan tugas kuliah" }
];